module.exports = {
	rules: {
		'arrow-body-style': ['error', 'always'],
		'arrow-parens': ['error', 'always'],
		'arrow-spacing': ['error', {'before': true, 'after': true}],
		'constructor-super': 'error',
		'generator-star-spacing': ['error', {'before': false, 'after': true}],
		'no-class-assign': 'error',
		'no-confusing-arrow': ['error', {'allowParens': false}],
		'no-const-assign': 'error',
		'no-dupe-class-members': 'error',
		'no-duplicate-imports': 'error',
		'no-new-symbol': 'error',
		'no-restricted-imports': 'off',
		'no-this-before-super': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-constructor': 'error',
		'no-useless-rename': 'error',
		'no-var': 'error',
		'object-shorthand': 'off',
		'prefer-arrow-callback': 'error',
		'prefer-const': 'error',
		'prefer-numeric-literals': 'off',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'require-yield': 'error',
		'rest-spread-spacing': ['error', 'never'],
		'sort-imports': ['error', {'ignoreCase': false, 'ignoreMemberSort': false, 'memberSyntaxSortOrder': ['none', 'all', 'multiple', 'single']}],
		'symbol-description': 'error',
		'template-curly-spacing': ['error', 'never'],
		'yield-star-spacing': ['error', {'before': false, 'after': true}]
	}
};
