module.exports = {
	rules: {
		'array-bracket-spacing': ['error', 'never'],
		'block-spacing': ['error', 'always'],
		'brace-style': ['error', '1tbs', {'allowSingleLine': false}],
		'camelcase': ['error', {'properties': 'always'}],
		'comma-dangle': 'error',
		'comma-spacing': ['error', {'before': false, 'after': true}],
		'comma-style': ['error', 'last'],
		'computed-property-spacing': ['error', 'never'],
		'consistent-this': ['off', 'self'],
		'eol-last': 'error',
		'func-call-spacing': ['error', 'never'],
		'func-name-matching': 'off',
		'func-names': 'off',
		'func-style': ['error', 'declaration'],
		'id-blacklist': 'off',
		'id-length': 'off',
		'id-match': 'off',
		'indent': ['error', 'tab', {'SwitchCase': 1}],
		'jsx-quotes': ['error', 'prefer-double'],
		'key-spacing': ['error', {'beforeColon': false, 'afterColon': true}],
		'keyword-spacing': ['error', {'before': true, 'after': true}],
		'line-comment-position': 'off',
		'linebreak-style': 'off',
		'lines-around-comment': ['error', {'beforeBlockComment': true, 'beforeLineComment': true, 'allowBlockStart': true, 'allowBlockEnd' : true}],
		'lines-around-directive': ['error', {'before': 'never', 'after': 'never'}],
		'max-depth': 'off',
		'max-len': 'off',
		'max-lines': 'off',
		'max-nested-callbacks': 'off',
		'max-params': 'off',
		'max-statements-per-line': ['error', {'max': 1}],
		'max-statements': 'off',
		'multiline-ternary': ['error', 'never'],
		'new-cap': 'error',
		'new-parens': 'error',
		'newline-after-var': ['error', 'always'],
		'newline-before-return': 'error',
		'newline-per-chained-call': 'off',
		'no-array-constructor': 'error',
		'no-bitwise': 'off',
		'no-continue': 'off',
		'no-inline-comments': 'off',
		'no-lonely-if': 'off',
		'no-mixed-spaces-and-tabs': 'error',
		'no-multiple-empty-lines': ['error', {'max': 1}],
		'no-negated-condition': 'error',
		'no-nested-ternary': 'off',
		'no-new-object': 'error',
		'no-plusplus': 'off',
		'no-restricted-syntax': 'off',
		'no-tabs': 'off',
		'no-ternary': 'off',
		'no-trailing-spaces': ['error', {'skipBlankLines': false}],
		'no-underscore-dangle': 'off',
		'no-unneeded-ternary': 'error',
		'no-whitespace-before-property': 'error',
		'object-curly-newline': ['error', {'multiline': true, 'minProperties': 1}],
		'object-curly-spacing': ['error', 'never'],
		'object-property-newline': 'error',
		'one-var-declaration-per-line': 'off',
		'one-var': ['error', 'always'],
		'operator-assignment': ['error', 'always'],
		'operator-linebreak': 'off',
		'padded-blocks': ['error', 'never'],
		'quote-props': ['error', 'always'],
		'quotes': ['error', 'single'],
		'require-jsdoc': 'off',
		'semi-spacing': ['error', {'before': false, 'after': true}],
		'semi': ['error', 'always'],
		'sort-keys': 'off',
		'sort-vars': 'off',
		'space-before-blocks': ['error', 'always'],
		'space-before-function-paren': ['error', 'never'],
		'space-in-parens': ['error', 'never'],
		'space-infix-ops': ['error', {'int32Hint': false}],
		'space-unary-ops': ['error', {'words': true, 'nonwords': false}],
		'spaced-comment': ['error', 'always'],
		'unicode-bom': ['error', 'never'],
		'wrap-regex': 'off'
	}
};
